#!/usr/bin/env python3
"""Apply rename map to standardize filenames."""

import os
import json

STAGE_DIR = "/Users/pengziran/development/pengyuexian/MoonSpeak/books/Oxford-Reading-Tree/Stage01"

# Rename map from AI output
rename_map = [
    {"from": "A Good Trick.txt", "to": "a_good_trick.txt"},
    {"from": "Big Feet.txt", "to": "big_feet.txt"},
    {"from": "Chip's Robot.txt", "to": "chip_s_robot.txt"},
    {"from": "Dad's Birthday.txt", "to": "dad_s_birthday.txt"},
    {"from": "Floppy Floppy.txt", "to": "floppy_floppy.txt"},
    {"from": "Floppy did this.txt", "to": "floppy_did_this.txt"},
    {"from": "Floppy's Bone.txt", "to": "floppy_s_bone.txt"},
    {"from": "Fun at the Beach.txt", "to": "fun_at_the_beach.txt"},
    {"from": "Funny Fish.txt", "to": "funny_fish.txt"},
    {"from": "Get Dad.txt", "to": "get_dad.txt"},
    {"from": "Go Away,Cat.txt", "to": "go_away_cat.txt"},
    {"from": "Go On ,Mum!.txt", "to": "go_on_mum.txt"},
    {"from": "Goal!.txt", "to": "goal.txt"},
    {"from": "Good Old Mum.txt", "to": "good_old_mum.txt"},
    {"from": "Hello Grandma.txt", "to": "hello_grandma.txt"},
    {"from": "Hide and Seek.txt", "to": "hide_and_seek.txt"},
    {"from": "I see.txt", "to": "i_see.txt"},
    {"from": "Kipper's Diary.txt", "to": "kipper_s_diary.txt"},
    {"from": "Making Faces.txt", "to": "making_faces.txt"},
    {"from": "Mum's New Hat.txt", "to": "mum_s_new_hat.txt"},
    {"from": "My Dad.txt", "to": "my_dad.txt"},
    {"from": "One Wheel.txt", "to": "one_wheel.txt"},
    {"from": "Picnic Time.txt", "to": "picnic_time.txt"},
    {"from": "See Me Skip.txt", "to": "see_me_skip.txt"},
    {"from": "Shopping.txt", "to": "shopping.txt"},
    {"from": "Silly Races.txt", "to": "silly_races.txt"},
    {"from": "The Apple.txt", "to": "the_apple.txt"},
    {"from": "The Box of Treasure.txt", "to": "the_box_of_treasure.txt"},
    {"from": "The Headache.txt", "to": "the_headache.txt"},
    {"from": "The Mud Pie.txt", "to": "the_mud_pie.txt"},
    {"from": "The Pancake.txt", "to": "the_pancake.txt"},
    {"from": "The Snowman.txt", "to": "the_snowman.txt"},
    {"from": "Top Dog.txt", "to": "top_dog.txt"},
    {"from": "Up you go.txt", "to": "up_you_go.txt"},
    {"from": "WHat a DIN!.txt", "to": "what_a_din.txt"},
    {"from": "What Dogs Like.txt", "to": "what_dogs_like.txt"},
    {"from": "What a Mess.txt", "to": "what_a_mess.txt"},
    {"from": "Where is Baby.txt", "to": "where_is_baby.txt"},
    {"from": "Who did that.txt", "to": "who_did_that.txt"},
    {"from": "getting up.txt", "to": "getting_up.txt"},
    {"from": "look out.txt", "to": "look_out.txt"},
    {"from": "the hedgehog.txt", "to": "the_hedgehog.txt"},
    {"from": "the lost teddy.txt", "to": "the_lost_teddy.txt"},
    {"from": "the street fair.txt", "to": "the_street_fair.txt"},
    {"from": "the swing ball.txt", "to": "the_swing_ball.txt"},
]

# Add the 【公益知识库zscc.club】 prefixed ones
prefixed_map = [
    {"from": "【公益知识库zscc.club】A Good Trick.mp3", "to": "a_good_trick.mp3"},
    {"from": "【公益知识库zscc.club】A good  trick.pdf", "to": "a_good_trick.pdf"},
    {"from": "【公益知识库zscc.club】At the part.pdf", "to": "at_the_part.pdf"},
    {"from": "【公益知识库zscc.club】Big Feet.mp3", "to": "big_feet.mp3"},
    {"from": "【公益知识库zscc.club】Big Feet.pdf", "to": "big_feet.pdf"},
    {"from": "【公益知识库zscc.club】Can You See Me.pdf", "to": "can_you_see_me.pdf"},
    {"from": "【公益知识库zscc.club】Chip's Robot.mp3", "to": "chip_s_robot.mp3"},
    {"from": "【公益知识库zscc.club】Chip's Robot.pdf", "to": "chip_s_robot.pdf"},
    {"from": "【公益知识库zscc.club】Dad's Birthday.mp3", "to": "dad_s_birthday.mp3"},
    {"from": "【公益知识库zscc.club】Dad's Birthday.pdf", "to": "dad_s_birthday.pdf"},
    {"from": "【公益知识库zscc.club】Fancy Dress.pdf", "to": "fancy_dress.pdf"},
    {"from": "【公益知识库zscc.club】Floppy Floppy.mp3", "to": "floppy_floppy.mp3"},
    {"from": "【公益知识库zscc.club】Floppy did this.mp3", "to": "floppy_did_this.mp3"},
    {"from": "【公益知识库zscc.club】Floppy did this.pdf", "to": "floppy_did_this.pdf"},
    {"from": "【公益知识库zscc.club】Floppy's Bone.mp3", "to": "floppy_s_bone.mp3"},
    {"from": "【公益知识库zscc.club】Floppy's Bone.pdf", "to": "floppy_s_bone.pdf"},
    {"from": "【公益知识库zscc.club】Fun at the Beach.mp3", "to": "fun_at_the_beach.mp3"},
    {"from": "【公益知识库zscc.club】Funny Fish.mp3", "to": "funny_fish.mp3"},
    {"from": "【公益知识库zscc.club】Funny Fish.pdf", "to": "funny_fish.pdf"},
    {"from": "【公益知识库zscc.club】Get Dad.mp3", "to": "get_dad.mp3"},
    {"from": "【公益知识库zscc.club】Get Dad.pdf", "to": "get_dad.pdf"},
    {"from": "【公益知识库zscc.club】Get On.pdf", "to": "get_on.pdf"},
    {"from": "【公益知识库zscc.club】Go Away Cat.pdf", "to": "go_away_cat.pdf"},
    {"from": "【公益知识库zscc.club】Go Away,Cat.mp3", "to": "go_away_cat.mp3"},
    {"from": "【公益知识库zscc.club】Go On ,Mum!.mp3", "to": "go_on_mum.mp3"},
    {"from": "【公益知识库zscc.club】Go On Mum.pdf", "to": "go_on_mum.pdf"},
    {"from": "【公益知识库zscc.club】Go away Floppy.pdf", "to": "go_away_floppy.pdf"},
    {"from": "【公益知识库zscc.club】Goal!.mp3", "to": "goal.mp3"},
    {"from": "【公益知识库zscc.club】Goal!.pdf", "to": "goal.pdf"},
    {"from": "【公益知识库zscc.club】Good Dog.pdf", "to": "good_dog.pdf"},
    {"from": "【公益知识库zscc.club】Good Old Mum.mp3", "to": "good_old_mum.mp3"},
    {"from": "【公益知识库zscc.club】Good Old Mum.pdf", "to": "good_old_mum.pdf"},
    {"from": "【公益知识库zscc.club】Hello Grandma.mp3", "to": "hello_grandma.mp3"},
    {"from": "【公益知识库zscc.club】Hello Grandma.pdf", "to": "hello_grandma.pdf"},
    {"from": "【公益知识库zscc.club】Hide and Seek.mp3", "to": "hide_and_seek.mp3"},
    {"from": "【公益知识库zscc.club】Hide and Seek.pdf", "to": "hide_and_seek.pdf"},
    {"from": "【公益知识库zscc.club】Hook a Duck.pdf", "to": "hook_a_duck.pdf"},
    {"from": "【公益知识库zscc.club】I See.pdf", "to": "i_see.pdf"},
    {"from": "【公益知识库zscc.club】I see.mp3", "to": "i_see.mp3"},
    {"from": "【公益知识库zscc.club】Is It.pdf", "to": "is_it.pdf"},
    {"from": "【公益知识库zscc.club】Kipper's Dairy.pdf", "to": "kipper_s_dairy.pdf"},
    {"from": "【公益知识库zscc.club】Kipper's Diary.mp3", "to": "kipper_s_diary.mp3"},
    {"from": "【公益知识库zscc.club】Look After Me.pdf", "to": "look_after_me.pdf"},
    {"from": "【公益知识库zscc.club】Look at Me.pdf", "to": "look_at_me.pdf"},
    {"from": "【公益知识库zscc.club】Making Faces.mp3", "to": "making_faces.mp3"},
    {"from": "【公益知识库zscc.club】Making Faces.pdf", "to": "making_faces.pdf"},
    {"from": "【公益知识库zscc.club】Mum's New Hat.mp3", "to": "mum_s_new_hat.mp3"},
    {"from": "【公益知识库zscc.club】Mum's New Hat.pdf", "to": "mum_s_new_hat.pdf"},
    {"from": "【公益知识库zscc.club】My Dad.mp3", "to": "my_dad.mp3"},
    {"from": "【公益知识库zscc.club】My Dad.pdf", "to": "my_dad.pdf"},
    {"from": "【公益知识库zscc.club】One Wheel.mp3", "to": "one_wheel.mp3"},
    {"from": "【公益知识库zscc.club】One Wheel.pdf", "to": "one_wheel.pdf"},
    {"from": "【公益知识库zscc.club】Picnic Time.mp3", "to": "picnic_time.mp3"},
    {"from": "【公益知识库zscc.club】Picnic Time.pdf", "to": "picnic_time.pdf"},
    {"from": "【公益知识库zscc.club】Presents for Dad.pdf", "to": "presents_for_dad.pdf"},
    {"from": "【公益知识库zscc.club】Push!.pdf", "to": "push.pdf"},
    {"from": "【公益知识库zscc.club】Reds and blues.pdf", "to": "reds_and_blues.pdf"},
    {"from": "【公益知识库zscc.club】See Me Skip.mp3", "to": "see_me_skip.mp3"},
    {"from": "【公益知识库zscc.club】See Me Skip.pdf", "to": "see_me_skip.pdf"},
    {"from": "【公益知识库zscc.club】Shopping.mp3", "to": "shopping.mp3"},
    {"from": "【公益知识库zscc.club】Shopping.pdf", "to": "shopping.pdf"},
    {"from": "【公益知识库zscc.club】Silly Races.mp3", "to": "silly_races.mp3"},
    {"from": "【公益知识库zscc.club】Silly Races.pdf", "to": "silly_races.pdf"},
    {"from": "【公益知识库zscc.club】The Apple.mp3", "to": "the_apple.mp3"},
    {"from": "【公益知识库zscc.club】The Box of Treasure.mp3", "to": "the_box_of_treasure.mp3"},
    {"from": "【公益知识库zscc.club】The Box of Treasure.pdf", "to": "the_box_of_treasure.pdf"},
    {"from": "【公益知识库zscc.club】The Headache.mp3", "to": "the_headache.mp3"},
    {"from": "【公益知识库zscc.club】The Headache.pdf", "to": "the_headache.pdf"},
    {"from": "【公益知识库zscc.club】The Ice Cream.pdf", "to": "the_ice_cream.pdf"},
    {"from": "【公益知识库zscc.club】The Journey.pdf", "to": "the_journey.pdf"},
    {"from": "【公益知识库zscc.club】The Mud Pie.mp3", "to": "the_mud_pie.mp3"},
    {"from": "【公益知识库zscc.club】The Mud Pie.pdf", "to": "the_mud_pie.pdf"},
    {"from": "【公益知识库zscc.club】The Pancake.mp3", "to": "the_pancake.mp3"},
    {"from": "【公益知识库zscc.club】The Pet Shop.pdf", "to": "the_pet_shop.pdf"},
    {"from": "【公益知识库zscc.club】The Sandcastle.pdf", "to": "the_sandcastle.pdf"},
    {"from": "【公益知识库zscc.club】The Snowman.mp3", "to": "the_snowman.mp3"},
    {"from": "【公益知识库zscc.club】The Snowman.pdf", "to": "the_snowman.pdf"},
    {"from": "【公益知识库zscc.club】The pancake.pdf", "to": "the_pancake.pdf"},
    {"from": "【公益知识库zscc.club】Top Dog.mp3", "to": "top_dog.mp3"},
    {"from": "【公益知识库zscc.club】Top Dog.pdf", "to": "top_dog.pdf"},
    {"from": "【公益知识库zscc.club】Up You Go.pdf", "to": "up_you_go.pdf"},
    {"from": "【公益知识库zscc.club】Up you go.mp3", "to": "up_you_go.mp3"},
    {"from": "【公益知识库zscc.club】WHat a DIN!.mp3", "to": "what_a_din.mp3"},
    {"from": "【公益知识库zscc.club】What Dogs Like.mp3", "to": "what_dogs_like.mp3"},
    {"from": "【公益知识库zscc.club】What Dogs Like.pdf", "to": "what_dogs_like.pdf"},
    {"from": "【公益知识库zscc.club】What a DIN!.pdf", "to": "what_a_din.pdf"},
    {"from": "【公益知识库zscc.club】What a Mess.mp3", "to": "what_a_mess.mp3"},
    {"from": "【公益知识库zscc.club】What a Mess.pdf", "to": "what_a_mess.pdf"},
    {"from": "【公益知识库zscc.club】Where is Baby.mp3", "to": "where_is_baby.mp3"},
    {"from": "【公益知识库zscc.club】Where is Baby.pdf", "to": "where_is_baby.pdf"},
    {"from": "【公益知识库zscc.club】Who did that.mp3", "to": "who_did_that.mp3"},
    {"from": "【公益知识库zscc.club】Who did that.pdf", "to": "who_did_that.pdf"},
    {"from": "【公益知识库zscc.club】floppy floppy.pdf", "to": "floppy_floppy.pdf"},
    {"from": "【公益知识库zscc.club】fun at the beach.pdf", "to": "fun_at_the_beach.pdf"},
    {"from": "【公益知识库zscc.club】getting up.mp3", "to": "getting_up.mp3"},
    {"from": "【公益知识库zscc.club】look out.mp3", "to": "look_out.mp3"},
    {"from": "【公益知识库zscc.club】the hedgehog.mp3", "to": "the_hedgehog.mp3"},
    {"from": "【公益知识库zscc.club】the lost teddy.mp3", "to": "the_lost_teddy.mp3"},
    {"from": "【公益知识库zscc.club】the street fair.mp3", "to": "the_street_fair.mp3"},
    {"from": "【公益知识库zscc.club】the swing ball.mp3", "to": "the_swing_ball.mp3"},
    {"from": "【公益知识库zscc.club】who is it.pdf", "to": "who_is_it.pdf"},
]

all_renames = rename_map + prefixed_map

# Apply renames
count = 0
for item in all_renames:
    src = os.path.join(STAGE_DIR, item["from"])
    dst = os.path.join(STAGE_DIR, item["to"])
    if os.path.exists(src) and src != dst:
        os.rename(src, dst)
        count += 1
        print(f"✓ {item['from']} → {item['to']}")

print(f"\n✅ Renamed {count} files")
print(f"\nRemaining files: {len(os.listdir(STAGE_DIR))}")
